<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" retried="10" total="17" passed="6">
  <reporter-output>
    <line>
      <![CDATA[********** Inside the @BeforeSuite where Chrome browser is getting instantiated]]>
    </line>
    <line>
      <![CDATA[********** End of the @BeforeSuite where Chrome browser is getting instantiated]]>
    </line>
    <line>
      <![CDATA[********** Inside the @BeforeTest where URL is entered and navigated to the target "Practice Form"]]>
    </line>
    <line>
      <![CDATA[********** Now navigating to the target "Pratice Form"]]>
    </line>
    <line>
      <![CDATA[********** End of the @BeforeTest where URL is entered and navigated to the target "Practice Form"]]>
    </line>
    <line>
      <![CDATA[********** Inside the @Test which uses [MethodAsDataProvider] data provider]]>
    </line>
    <line>
      <![CDATA[********** End of the @Test which uses [ExcelAsDataProvider] data provider]]>
    </line>
    <line>
      <![CDATA[********** Inside the @Test which uses [MethodAsDataProvider] data provider]]>
    </line>
    <line>
      <![CDATA[********** Inside the @Test which uses [MethodAsDataProvider] data provider]]>
    </line>
    <line>
      <![CDATA[********** Inside the @Test which uses [MethodAsDataProvider] data provider]]>
    </line>
    <line>
      <![CDATA[********** Inside the @Test which uses [MethodAsDataProvider] data provider]]>
    </line>
    <line>
      <![CDATA[********** Inside the @Test which uses [MethodAsDataProvider] data provider]]>
    </line>
    <line>
      <![CDATA[********** Inside the @Test which uses [MethodAsDataProvider] data provider]]>
    </line>
    <line>
      <![CDATA[********** Inside the @Test which uses [MethodAsDataProvider] data provider]]>
    </line>
    <line>
      <![CDATA[********** Inside the @Test which uses [MethodAsDataProvider] data provider]]>
    </line>
    <line>
      <![CDATA[********** Inside the @Test which uses [MethodAsDataProvider] data provider]]>
    </line>
    <line>
      <![CDATA[********** Inside the @Test which uses [MethodAsDataProvider] data provider]]>
    </line>
    <line>
      <![CDATA[********** Inside the @Test which uses [MethodAsDataProvider] data provider]]>
    </line>
    <line>
      <![CDATA[********** Inside the @Test which uses [ExcelAsDataProvider] data provider]]>
    </line>
    <line>
      <![CDATA[********** End of the @Test which uses [ExcelAsDataProvider] data provider]]>
    </line>
    <line>
      <![CDATA[********** Inside the @Test which uses [ExcelAsDataProvider] data provider]]>
    </line>
    <line>
      <![CDATA[********** End of the @Test which uses [ExcelAsDataProvider] data provider]]>
    </line>
    <line>
      <![CDATA[********** Inside the @Test which uses [ExcelAsDataProvider] data provider]]>
    </line>
    <line>
      <![CDATA[********** End of the @Test which uses [ExcelAsDataProvider] data provider]]>
    </line>
    <line>
      <![CDATA[********** Inside the @Test which uses [ExcelAsDataProvider] data provider]]>
    </line>
    <line>
      <![CDATA[********** End of the @Test which uses [ExcelAsDataProvider] data provider]]>
    </line>
    <line>
      <![CDATA[********** Inside the @Test which uses [ExcelAsDataProvider] data provider]]>
    </line>
    <line>
      <![CDATA[********** End of the @Test which uses [ExcelAsDataProvider] data provider]]>
    </line>
    <line>
      <![CDATA[********** Inside the @AfterSuite where Chrome browser is getting closed]]>
    </line>
    <line>
      <![CDATA[********** Outside the @AfterSuite where Chrome browser is getting closed]]>
    </line>
  </reporter-output>
  <suite name="Suite_Framework" duration-ms="136460" started-at="2021-02-05T10:06:13 UTC" finished-at="2021-02-05T10:08:29 UTC">
    <groups>
    </groups>
    <test name="Test_Framework" duration-ms="136460" started-at="2021-02-05T10:06:13 UTC" finished-at="2021-02-05T10:08:29 UTC">
      <class name="framework.excel.TestNG_with_ExcelDataProvider">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:framework.excel.TestNG_with_ExcelDataProvider@7e0e6aa2]" name="beforeSuite" is-config="true" duration-ms="2634" started-at="2021-02-05T10:06:10 UTC" finished-at="2021-02-05T10:06:13 UTC">
          <reporter-output>
            <line>
              <![CDATA[********** Inside the @BeforeSuite where Chrome browser is getting instantiated]]>
            </line>
            <line>
              <![CDATA[********** End of the @BeforeSuite where Chrome browser is getting instantiated]]>
            </line>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:framework.excel.TestNG_with_ExcelDataProvider@7e0e6aa2]" name="beforeTest" is-config="true" duration-ms="18729" started-at="2021-02-05T10:06:13 UTC" finished-at="2021-02-05T10:06:31 UTC">
          <reporter-output>
            <line>
              <![CDATA[********** Inside the @BeforeTest where URL is entered and navigated to the target "Practice Form"]]>
            </line>
            <line>
              <![CDATA[********** Now navigating to the target "Pratice Form"]]>
            </line>
            <line>
              <![CDATA[********** End of the @BeforeTest where URL is entered and navigated to the target "Practice Form"]]>
            </line>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="Diff(int, int, int)[pri:0, instance:framework.excel.TestNG_with_ExcelDataProvider@7e0e6aa2]" name="Diff" duration-ms="7" started-at="2021-02-05T10:06:31 UTC" data-provider="MethodAsDataProvider" finished-at="2021-02-05T10:06:31 UTC">
          <params>
            <param index="0">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-1]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[********** Inside the @Test which uses [MethodAsDataProvider] data provider]]>
            </line>
            <line>
              <![CDATA[********** End of the @Test which uses [ExcelAsDataProvider] data provider]]>
            </line>
          </reporter-output>
        </test-method> <!-- Diff -->
        <test-method status="SKIP" signature="Diff(int, int, int)[pri:0, instance:framework.excel.TestNG_with_ExcelDataProvider@7e0e6aa2]" name="Diff" duration-ms="2" retried="true" started-at="2021-02-05T10:06:31 UTC" data-provider="MethodAsDataProvider" finished-at="2021-02-05T10:06:31 UTC">
          <params>
            <param index="0">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[7]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-18]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [-2] but found [-18]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [-2] but found [-18]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at framework.excel.TestNG_with_ExcelDataProvider.Diff(TestNG_with_ExcelDataProvider.java:205)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[********** Inside the @Test which uses [MethodAsDataProvider] data provider]]>
            </line>
          </reporter-output>
        </test-method> <!-- Diff -->
        <test-method status="SKIP" signature="Diff(int, int, int)[pri:0, instance:framework.excel.TestNG_with_ExcelDataProvider@7e0e6aa2]" name="Diff" duration-ms="2" retried="true" started-at="2021-02-05T10:06:31 UTC" data-provider="MethodAsDataProvider" finished-at="2021-02-05T10:06:31 UTC">
          <params>
            <param index="0">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[7]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-18]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [-2] but found [-18]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [-2] but found [-18]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at framework.excel.TestNG_with_ExcelDataProvider.Diff(TestNG_with_ExcelDataProvider.java:205)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[********** Inside the @Test which uses [MethodAsDataProvider] data provider]]>
            </line>
          </reporter-output>
        </test-method> <!-- Diff -->
        <test-method status="SKIP" signature="Diff(int, int, int)[pri:0, instance:framework.excel.TestNG_with_ExcelDataProvider@7e0e6aa2]" name="Diff" duration-ms="1" retried="true" started-at="2021-02-05T10:06:31 UTC" data-provider="MethodAsDataProvider" finished-at="2021-02-05T10:06:31 UTC">
          <params>
            <param index="0">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[7]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-18]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [-2] but found [-18]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [-2] but found [-18]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at framework.excel.TestNG_with_ExcelDataProvider.Diff(TestNG_with_ExcelDataProvider.java:205)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[********** Inside the @Test which uses [MethodAsDataProvider] data provider]]>
            </line>
          </reporter-output>
        </test-method> <!-- Diff -->
        <test-method status="SKIP" signature="Diff(int, int, int)[pri:0, instance:framework.excel.TestNG_with_ExcelDataProvider@7e0e6aa2]" name="Diff" duration-ms="1" retried="true" started-at="2021-02-05T10:06:31 UTC" data-provider="MethodAsDataProvider" finished-at="2021-02-05T10:06:31 UTC">
          <params>
            <param index="0">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[7]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-18]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [-2] but found [-18]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [-2] but found [-18]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at framework.excel.TestNG_with_ExcelDataProvider.Diff(TestNG_with_ExcelDataProvider.java:205)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[********** Inside the @Test which uses [MethodAsDataProvider] data provider]]>
            </line>
          </reporter-output>
        </test-method> <!-- Diff -->
        <test-method status="SKIP" signature="Diff(int, int, int)[pri:0, instance:framework.excel.TestNG_with_ExcelDataProvider@7e0e6aa2]" name="Diff" duration-ms="1" retried="true" started-at="2021-02-05T10:06:31 UTC" data-provider="MethodAsDataProvider" finished-at="2021-02-05T10:06:31 UTC">
          <params>
            <param index="0">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[7]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-18]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [-2] but found [-18]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [-2] but found [-18]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at framework.excel.TestNG_with_ExcelDataProvider.Diff(TestNG_with_ExcelDataProvider.java:205)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[********** Inside the @Test which uses [MethodAsDataProvider] data provider]]>
            </line>
          </reporter-output>
        </test-method> <!-- Diff -->
        <test-method status="SKIP" signature="Diff(int, int, int)[pri:0, instance:framework.excel.TestNG_with_ExcelDataProvider@7e0e6aa2]" name="Diff" duration-ms="1" retried="true" started-at="2021-02-05T10:06:31 UTC" data-provider="MethodAsDataProvider" finished-at="2021-02-05T10:06:31 UTC">
          <params>
            <param index="0">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[7]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-18]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [-2] but found [-18]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [-2] but found [-18]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at framework.excel.TestNG_with_ExcelDataProvider.Diff(TestNG_with_ExcelDataProvider.java:205)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[********** Inside the @Test which uses [MethodAsDataProvider] data provider]]>
            </line>
          </reporter-output>
        </test-method> <!-- Diff -->
        <test-method status="SKIP" signature="Diff(int, int, int)[pri:0, instance:framework.excel.TestNG_with_ExcelDataProvider@7e0e6aa2]" name="Diff" duration-ms="1" retried="true" started-at="2021-02-05T10:06:31 UTC" data-provider="MethodAsDataProvider" finished-at="2021-02-05T10:06:31 UTC">
          <params>
            <param index="0">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[7]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-18]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [-2] but found [-18]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [-2] but found [-18]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at framework.excel.TestNG_with_ExcelDataProvider.Diff(TestNG_with_ExcelDataProvider.java:205)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[********** Inside the @Test which uses [MethodAsDataProvider] data provider]]>
            </line>
          </reporter-output>
        </test-method> <!-- Diff -->
        <test-method status="SKIP" signature="Diff(int, int, int)[pri:0, instance:framework.excel.TestNG_with_ExcelDataProvider@7e0e6aa2]" name="Diff" duration-ms="1" retried="true" started-at="2021-02-05T10:06:31 UTC" data-provider="MethodAsDataProvider" finished-at="2021-02-05T10:06:31 UTC">
          <params>
            <param index="0">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[7]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-18]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [-2] but found [-18]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [-2] but found [-18]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at framework.excel.TestNG_with_ExcelDataProvider.Diff(TestNG_with_ExcelDataProvider.java:205)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[********** Inside the @Test which uses [MethodAsDataProvider] data provider]]>
            </line>
          </reporter-output>
        </test-method> <!-- Diff -->
        <test-method status="SKIP" signature="Diff(int, int, int)[pri:0, instance:framework.excel.TestNG_with_ExcelDataProvider@7e0e6aa2]" name="Diff" duration-ms="1" retried="true" started-at="2021-02-05T10:06:31 UTC" data-provider="MethodAsDataProvider" finished-at="2021-02-05T10:06:31 UTC">
          <params>
            <param index="0">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[7]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-18]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [-2] but found [-18]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [-2] but found [-18]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at framework.excel.TestNG_with_ExcelDataProvider.Diff(TestNG_with_ExcelDataProvider.java:205)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[********** Inside the @Test which uses [MethodAsDataProvider] data provider]]>
            </line>
          </reporter-output>
        </test-method> <!-- Diff -->
        <test-method status="SKIP" signature="Diff(int, int, int)[pri:0, instance:framework.excel.TestNG_with_ExcelDataProvider@7e0e6aa2]" name="Diff" duration-ms="1" retried="true" started-at="2021-02-05T10:06:31 UTC" data-provider="MethodAsDataProvider" finished-at="2021-02-05T10:06:31 UTC">
          <params>
            <param index="0">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[7]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-18]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [-2] but found [-18]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [-2] but found [-18]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at framework.excel.TestNG_with_ExcelDataProvider.Diff(TestNG_with_ExcelDataProvider.java:205)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[********** Inside the @Test which uses [MethodAsDataProvider] data provider]]>
            </line>
          </reporter-output>
        </test-method> <!-- Diff -->
        <test-method status="FAIL" signature="Diff(int, int, int)[pri:0, instance:framework.excel.TestNG_with_ExcelDataProvider@7e0e6aa2]" name="Diff" duration-ms="1" started-at="2021-02-05T10:06:31 UTC" data-provider="MethodAsDataProvider" finished-at="2021-02-05T10:06:31 UTC">
          <params>
            <param index="0">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[7]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-18]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [-2] but found [-18]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [-2] but found [-18]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at framework.excel.TestNG_with_ExcelDataProvider.Diff(TestNG_with_ExcelDataProvider.java:205)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[********** Inside the @Test which uses [MethodAsDataProvider] data provider]]>
            </line>
          </reporter-output>
        </test-method> <!-- Diff -->
        <test-method status="PASS" signature="Registration_data(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:framework.excel.TestNG_with_ExcelDataProvider@7e0e6aa2]" name="Registration_data" duration-ms="23174" started-at="2021-02-05T10:06:34 UTC" data-provider="ExcelAsDataProvider" finished-at="2021-02-05T10:06:57 UTC">
          <params>
            <param index="0">
              <value>
                <![CDATA[Jimmy]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Person-1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[jimmyP1@xyz.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[9576843458]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[********** Inside the @Test which uses [ExcelAsDataProvider] data provider]]>
            </line>
            <line>
              <![CDATA[********** End of the @Test which uses [ExcelAsDataProvider] data provider]]>
            </line>
          </reporter-output>
        </test-method> <!-- Registration_data -->
        <test-method status="PASS" signature="Registration_data(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:framework.excel.TestNG_with_ExcelDataProvider@7e0e6aa2]" name="Registration_data" duration-ms="23026" started-at="2021-02-05T10:06:57 UTC" data-provider="ExcelAsDataProvider" finished-at="2021-02-05T10:07:20 UTC">
          <params>
            <param index="0">
              <value>
                <![CDATA[Carol]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Person-2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[carolP2@abc.ol]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[1223]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[********** Inside the @Test which uses [ExcelAsDataProvider] data provider]]>
            </line>
            <line>
              <![CDATA[********** End of the @Test which uses [ExcelAsDataProvider] data provider]]>
            </line>
          </reporter-output>
        </test-method> <!-- Registration_data -->
        <test-method status="PASS" signature="Registration_data(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:framework.excel.TestNG_with_ExcelDataProvider@7e0e6aa2]" name="Registration_data" duration-ms="23046" started-at="2021-02-05T10:07:20 UTC" data-provider="ExcelAsDataProvider" finished-at="2021-02-05T10:07:43 UTC">
          <params>
            <param index="0">
              <value>
                <![CDATA[Henry]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Person-3]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[henryP3@qqq.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[4089]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[********** Inside the @Test which uses [ExcelAsDataProvider] data provider]]>
            </line>
            <line>
              <![CDATA[********** End of the @Test which uses [ExcelAsDataProvider] data provider]]>
            </line>
          </reporter-output>
        </test-method> <!-- Registration_data -->
        <test-method status="PASS" signature="Registration_data(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:framework.excel.TestNG_with_ExcelDataProvider@7e0e6aa2]" name="Registration_data" duration-ms="23060" started-at="2021-02-05T10:07:43 UTC" data-provider="ExcelAsDataProvider" finished-at="2021-02-05T10:08:06 UTC">
          <params>
            <param index="0">
              <value>
                <![CDATA[Helen]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Person-4]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[helenP4@xyz.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[6578]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[********** Inside the @Test which uses [ExcelAsDataProvider] data provider]]>
            </line>
            <line>
              <![CDATA[********** End of the @Test which uses [ExcelAsDataProvider] data provider]]>
            </line>
          </reporter-output>
        </test-method> <!-- Registration_data -->
        <test-method status="PASS" signature="Registration_data(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:framework.excel.TestNG_with_ExcelDataProvider@7e0e6aa2]" name="Registration_data" duration-ms="23035" started-at="2021-02-05T10:08:06 UTC" data-provider="ExcelAsDataProvider" finished-at="2021-02-05T10:08:29 UTC">
          <params>
            <param index="0">
              <value>
                <![CDATA[Murray]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Person-5]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[murrayP@xyz.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[2222]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[********** Inside the @Test which uses [ExcelAsDataProvider] data provider]]>
            </line>
            <line>
              <![CDATA[********** End of the @Test which uses [ExcelAsDataProvider] data provider]]>
            </line>
          </reporter-output>
        </test-method> <!-- Registration_data -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:framework.excel.TestNG_with_ExcelDataProvider@7e0e6aa2]" name="afterSuite" is-config="true" duration-ms="73" started-at="2021-02-05T10:08:29 UTC" finished-at="2021-02-05T10:08:29 UTC">
          <reporter-output>
            <line>
              <![CDATA[********** Inside the @AfterSuite where Chrome browser is getting closed]]>
            </line>
            <line>
              <![CDATA[********** Outside the @AfterSuite where Chrome browser is getting closed]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- framework.excel.TestNG_with_ExcelDataProvider -->
    </test> <!-- Test_Framework -->
  </suite> <!-- Suite_Framework -->
</testng-results>
